//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurant.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class anasayfa
    {
        public int id { get; set; }
        public string ad { get; set; }
        public string tel { get; set; }
        public string acikGun { get; set; }
        public string acikSaat { get; set; }
        public string slogan { get; set; }
        public string arkaPlan { get; set; }
        public string videoLink { get; set; }
        public string adres { get; set; }
        public string eposta { get; set; }
        public string harita { get; set; }
        public string instagram { get; set; }
        public string twitter { get; set; }
        public string facebook { get; set; }
    }
}
