//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurant.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class galeri
    {
        public int id { get; set; }
        public string resimYolu { get; set; }
        public string alt { get; set; }
        public Nullable<bool> onay { get; set; }
    }
}
