//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurant.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sef
    {
        public int id { get; set; }
        public string isim { get; set; }
        public string soyisim { get; set; }
        public string kidem { get; set; }
        public string instagram { get; set; }
        public string twitter { get; set; }
        public string facebook { get; set; }
        public string foto { get; set; }
    }
}
